on:
  push:
    branches: [main]
    paths:
      - "src/**"
      - "**.rs"
      - "Cargo.toml"
      - "Dockerfile"
      - ".github/**"
  workflow_dispatch: # Enable manual triggering.

name: Deploy to GCP
jobs:
  docker:
    name: Upload Docker Image
    runs-on: ubuntu-latest

    outputs:
      image: ${{ steps.dbp.outputs.imageid }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          default: true

      # Ensure action works on repos that .gitignore Cargo.lock
      - name: Validate Cargo.lock
        run: |
          if ! [ -f "./Cargo.lock" ]; then
            cargo build --release --all-features
          fi

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push
        id: dbp
        uses: docker/build-push-action@v5
        with:
          context: . # To ensure that Cargo.lock is present from prior build step.
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ vars.DOCKERHUB_REPOSITORY }}:latest
          build-args: |
            "DISCORD_TOKEN=${{ secrets.DISCORD_TOKEN }}"
  gcp:
    name: Deploy to GCP
    runs-on: ubuntu-latest
    needs: docker

    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

      - name: Deploy Docker Image to GCP
        id: deploy
        uses: google-github-actions/deploy-cloudrun@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          region: ${{ vars.GCP_SERVICE_REGION }}
          image: ${{ secrets.DOCKERHUB_USERNAME }}/${{ vars.DOCKERHUB_REPOSITORY }}:latest
          service: discord-bot
