on:
  push:
    branches:
      - "main"

name: Deploy to GCP
jobs:
  docker:
    name: Upload Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          default: true

      # Ensure action works on repos that .gitignore Cargo.lock
      - name: Validate Cargo.lock
        run: |
          if ! [ -f "./Cargo.lock" ]; then
            cargo build --release --all-features
          fi

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push
        uses: docker/build-push-action@v5
        with:
          context: . # To ensure that Cargo.lock is present from prior build step.
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ vars.DOCKERHUB_REPOSITORY }}:latest
